version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dashboard_frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
